# Generated by Django 3.2.12 on 2022-04-05 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220327_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
