# Generated by Django 3.2.12 on 2022-04-13 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='種類'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='サイズ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{6})$')], verbose_name='色'),
        ),
    ]
