# Generated by Django 3.2.12 on 2022-05-11 08:22

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220427_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='承認済み'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.CharField(max_length=1000, validators=[shop.models.validate_bad_word], verbose_name='コメント'),
        ),
    ]
