# Generated by Django 3.2.12 on 2022-05-17 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220511_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日時')),
                ('name', models.CharField(max_length=100, verbose_name='商品カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日時')),
                ('name', models.CharField(max_length=100, verbose_name='商品カテゴリ名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categoryparent', verbose_name='所属親カテゴリ')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='所属カテゴリ'),
        ),
    ]
